---
title: "Publications"
---

### Metrics

- **Total publications:** 35  
- **First author:** 9  
- **Corresponding author:** 11  
- **H-index:** 15  

Full list:  
https://scholar.google.es/citations?user=HlIT1ekAAAAJ

---

### Selected publication

**Castelán-Sánchez, H. G.**, & Poon, A. F. (2025). Phylogenetic discordance can substantially overestimate genomic reassortment in avian influenza virus. bioRxiv, 2025-02.

**Castelán-Sánchez, H. G.**, Delaye, L., Inward, R. P., Dellicour, S., Gutierrez, B., Martinez de la Vina, N., ... & Escalera Zamudio, M. (2023). Comparing the evolutionary dynamics of predominant SARS-CoV-2 virus lineages co-circulating in Mexico. *Elife*, 12, e82069.

**Castelán-Sánchez, H. G.**, Martínez-Castilla, L. P., Sganzerla-Martínez, G., Torres-Flores, J., & López-Leal, G. (2022). Genome evolution and early introductions of the SARS-CoV-2 Omicron variant in Mexico. *Virus evolution*, 8(2), veac109.

Gutierrez, B., **Castelán-Sánchez, H. G.**, da Silva Candido, D., Jackson, B., Fleishon, S., Houzet, R., ... & Escalera-Zamudio, M. (2022). Emergence and widespread circulation of a recombinant SARS-CoV-2 lineage in North America. Cell Host & Microbe, 30(8), 1112-1123.

Rojas-Vargas, J., **Castelán-Sánchez, H. G.**, & Pardo-López, L. (2023). HADEG: a curated hydrocarbon aerobic degradation enzymes and genes database. *Computational Biology and Chemistry*, 107, 107966. 

**Castelán-Sánchez, H. G.**, Lopéz-Rosas, I., García-Suastegui, W. A., Peralta, R., Dobson, A. D., Batista-García, R. A., & Dávila-Ramos, S. (2019). Extremophile deep-sea viral communities from hydrothermal vents: Structural and functional analysis. *Marine Genomics*, 46, 16-28.









## 2026

⭐ **Corresponding author**

1. ⭐ Navarro, A., Rodea, G. E., de la Cruz-Montoya, A. H., Díaz-Velásquez, C. E., Vaca-Paniagua, F., Navarro-Cid del Prado, A., ... **Castelán-Sánchez, H. G.** (2026).  
Gut microbiota composition in adolescents from Mexico City: associations with nutritional and socioeconomic factors.  
*Molecular Nutrition & Food Research.*
https://onlinelibrary.wiley.com/doi/10.1002/mnfr.70386

2. Cano-Serrano, S., **Castelán-Sánchez, H. G.**, Oyaregui-Cabrera, H., Hernández, L. G., Pérez-Pérez, M. C., Santoyo, G., & Orozco-Mosqueda, M. D. C. (2026).  
Assessment of bacterial diversity and rhizospheric community shifts in maize grown in soils with contrasting productivity levels.  
*Plants.*
https://www.mdpi.com/2223-7747/15/1/130


---

## 2025

⭐ **Corresponding author**

1. Arce-Aceves, M. F., Espinosa-Neira, R., Mata-Espinosa, D. A., Barrios-Payan, J. A., **Castelán-Sánchez, H. G.**, et al. (2025).  
Fitness costs of *Mycobacterium tuberculosis* resistant to rifampicin is compensated by rapid Th2 polarization during infection.  
*Scientific Reports.*  
https://www.nature.com/articles/s41598-024-81446-3

2. ⭐ **Castelán-Sánchez, H. G.**, Fernández Dodero, J. V., Rojas-Vargas, J., Martínez-Ocampo, F., Hurtado-Ramírez, J. M., et al. (2025).  
Thermophilic *Pseudomonas aeruginosa* strain Ch39 isolated from hot springs in Puebla, Mexico.  
*Letters in Applied Microbiology.*  
https://academic.oup.com/lambio/article/78/4/ovaf059/8114799

3. ⭐ Pila-Lacuta, S., Pauccar, D., Rojas-Vargas, J., Rodríguez-Cruz, U. E., Sierra, J. L., **Castelán-Sánchez, H. G.**, & Quispe-Ricalde, M. A. (2025).  
Isolation of an arsenic-resistant *Halomonas elongata* strain from hypersaline systems in the Peruvian Andes.  
*PLOS ONE.*  
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0320639

4. ⭐ Sánchez-Corona, C. G., Gonzalez-Avila, L. U., Hernández-Cortez, C., Rojas-Vargas, J., Castro-Escarpulli, G., & **Castelán-Sánchez, H. G.** (2025).  
Impact of heavy metal resistance genes on antimicrobial resistance: ecological and public health implications.  
*Genes.*  
https://www.mdpi.com/2073-4425/16/6/625

5. Hernández-Villegas, E. N., **Castelán-Sánchez, H. G.**, Moreira-Soto, A., et al. (2025).  
Characterization of the virome in mosquitoes across habitats in the Yucatán Peninsula, Mexico.  
*Viruses.*  
https://www.mdpi.com/1999-4915/17/6/758

6. Pacheco-Ramírez, C. E., Prado-Guzmán, I. S., Navarrete-Bolaños, J. L., et al. (2025).  
Volatile compounds and genomic features of the endophyte *Bacillus velezensis* ITCE1.  
*Physiological and Molecular Plant Pathology.*  
https://doi.org/10.1016/j.pmpp.2025.102867




